package: simpleshop
version: '0.1'
author: FriendsOfREDAXO
compile: 1

page:
    title: Simpleshop
    perm: shop[]
    pjax: false
    icon: rex-icon fa-shopping-cart
    subpages:
        settings:
            title: translate:settings
            perm: shop[settings]
        variants:
            title: translate:label.variants
            hidden: true


requires:
    redaxo: '>=5.2'
    packages:
        yform: '>=1.1-beta1'