package: simpleshop
version: '2.0'
author: FriendsOfREDAXO
debug_email: dev@kreatif.it
compile: 0

page:
    title: Simpleshop
    perm: shop[]
    pjax: false
    icon: rex-icon fa-shopping-cart
    subpages:
        orders_export:
            title: translate:orders_export
            perm: shop[orders_export]
        settings:
            title: translate:settings
            perm: shop[settings]
        variants:
            title: translate:label.variants
            hidden: true
        packing_list:
            title: packing_list
            hidden: true



requires:
    redaxo: '>=5.2'
    packages:
        yform: '>=1.1-beta1'
        yform/manager: '>=2.0'
        sprog: '>=1.0.0-beta4'