package: simpleshop
version: '3.0'
author: FriendsOfREDAXO
debug_email: dev@kreatif.it
compile: 0

page:
    title: Simpleshop
    perm: shop[]
    pjax: false
    icon: rex-icon fa-shopping-cart
    subpages:
        orders_export:
            title: translate:orders_export
            perm: shop[orders_export]
        settings:
            title: translate:settings
            perm: shop[settings]
        variants:
            title: translate:label.variants
            hidden: true
        packing_list:
            title: packing_list
            hidden: true



requires:
    redaxo: '>=5.3'
    packages:
        yform: '^2.3'
        yform/manager: '^2.3'
        sprog: '^1.0'
        kreatif: '^3.1'