package: simpleshop
version: '5.5.5'
author: FriendsOfREDAXO
debug_email: dev@kreatif.it
compile: 0

page:
    title: Simpleshop
    perm: shop[]
    pjax: false
    icon: rex-icon fa-shopping-cart
    subpages:
        settings:
            title: translate:settings
        variants:
            title: translate:label.variants
            hidden: true
        yform_functions:
            title: yform_functions
            hidden: true
        orders_export:
            title: translate:orders_export
            perm: shop[orders_export]
        settings_adv:
            title: translate:label.advanced_settings
            perm: shop[advanced_settings]


requires:
    packages:
        yform: '>=3.3,<4' #needed commit: 4d45fc8b344033f1ce740253923d5369d60be6a6
        sprog: '^1.0'
        kreatif: '>=4.13'